---
datacenter: "dal12"
machine_type: "b3c.4x16"
hardware: "shared"
private_vlan_id: "2863552"
public_vlan_id: "2863550"
cluster_name: "oliver-ocp-4-6"
default_worker_pool_size: 2
entitlement: cloud_pak
kube_version: "4.6.17_openshift"